name          'alphagov-aptmirror'
version       '0.0.1'
source        'https://github.com/alphagov/puppet-aptmirror'
author        'alphagov'
license       'MIT'
summary       'Manage mirrors of apt repositories using apt-mirror'
description   'Manage mirrors of apt repositories using apt-mirror'
project_page  'https://github.com/alphagov/puppet-aptmirror'

dependency 'puppetlabs/stdlib', '>= 3.0.0'
